filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /log/*.log

output.logstash:
  hosts: ["ej2-logstash:5045"]
